### ISSUE TITLE
job-harbor failing 

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-tasks#55]
**Describe the bug:** 
the job 'job-harbor' crashes when deployed (image: otomi/tasks:v0.2.21). 
See here the last part of redacted logs:

```
Found: secret harbor-pullsecret in namespace xxx
Deleting secret/harbor-pullsecret from xxx namespace
Found: secret harbor-pullsecret in namespace xxx
Deleting secret/harbor-pullsecret from xxx namespace
{
  errors: [
    {
      code: 'CONFLICT',
      message: 'The project member specified already exist'
    }
  ]
}
Associating "project-admin" role for "team-admin" with harbor project "xxx" > already exists.
{
  errors: [
    {
      code: 'CONFLICT',
      message: 'The project member specified already exist'
    }
  ]
}
Associating "project-admin" role for "team-admin" with harbor project "xxx" > already exists.
{
  errors: [
    {
      code: 'CONFLICT',
      message: 'The project member specified already exist'
    }
  ]
}
Associating "project-admin" role for "team-admin" with harbor project "team-xxx" > already exists.
Found: secret harbor-pullsecret in namespace team-xxx
Deleting secret/harbor-pullsecret from team-xxx namespace
Found: secret harbor-pullsecret in namespace team-xxx
Deleting secret/harbor-pullsecret from team-xxx namespace
Found: secret harbor-pullsecret in namespace team-xxx
Deleting secret/harbor-pullsecret from team-xxx namespace
Found: secret harbor-pullsecret in namespace team-xxx
Deleting secret/harbor-pullsecret from team-xxx namespace
Found: secret harbor-pullsecret in namespace team-xxx
Deleting secret/harbor-pullsecret from team-xxx namespace
Found: secret harbor-pullsecret in namespace team-xxx
Deleting secret/harbor-pullsecret from team-xxx namespace
Deleting previous robot account otomi-team-xxx-pull
Deleting previous robot account otomi-team-xxx-pull
Deleting previous robot account otomi-team-xxx-pull
Deleting previous robot account otomi-team-xxx-pull
Deleting previous robot account otomi-team-xxx-pull
Deleting previous robot account otomi-team-xxx-pull
Creating robot account otomi-team-xxx-pull with project level perms
Deleting previous robot account otomi-team-xxx-pull
Creating robot account otomi-team-xxx-pull with project level perms
Creating robot account otomi-team-xxx-pull with project level perms
RobotCreated {
  id: undefined,
  name: undefined,
  secret: undefined,
  creationTime: undefined,
  expiresAt: undefined
}
Creating robot account otomi-team-xxx-pull with project level perms > already exists.
Creating secret/harbor-pullsecret at team-xxx namespace
/app/dist/tasks/harbor/harbor.js:176
        username: robotAccount.name,
                               ^

TypeError: Cannot read property 'name' of undefined
    at ensureTeamRobotAccountSecret (/app/dist/tasks/harbor/harbor.js:176:32)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /app/dist/tasks/harbor/harbor.js:216:9
    at async Promise.all (index 8)
    at async main (/app/dist/tasks/harbor/harbor.js:189:5)
```

**To Reproduce**
Not sure, I logged into harbor and couldnt find any 'undefined' robot account 

**Expected behavior:** 
job-harbor to complete succesfully

**Cluster(s):**
AKS 1.21.2
Otomi v0.15.3

**Comment by Morriz** [comment]
Wow, I have _never_ seen such duplication. Each action done 6 times it seems. How on earth did you manage that?

**Comment by Morriz** [comment]
We can only help with reports that bring reproducible steps, so if you can provide those, then please

**Comment by bartusz01** [comment]
Same issue appears today when running this job, but it doesnt succeed even after a few times. Because of this issue, the harbor-pullsecrets dont get created anymore
